apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: esb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: registry.tritux.com/easybulk3/front:v3.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-registry-secret
