apiVersion: v1
kind: ConfigMap
metadata:
  name: esb-back-env
  namespace: esb
data:
  SERVER_PORT: "9000"
  V1API: "v1"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.esb.svc.cluster.local:6446/easybulk?useSSL=false&allowPublicKeyRetrieval=true"
  #SPRING_DATASOURCE_USERNAME: "ebs-app"
  #SPRING_DATASOURCE_PASSWORD: "root1"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_CHARACTER_ENCODING: "utf-8"
  SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_CHARSET: "utf-8"
  SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_USEUNICODE: "true"
  SERVER_TOMCAT_URI_ENCODING: "UTF-8"
  SERVER_SERVLET_ENCODING_CHARSET: "UTF-8"
  SERVER_SERVLET_ENCODING_ENABLED: "true"
  SERVER_SERVLET_ENCODING_FORCE: "true"
  SPRING_SERVLET_MULTIPART_ENABLED: "true"
  SPRING_SERVLET_MULTIPART_FILE_SIZE_THRESHOLD: "30MB"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "30MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "30MB"
  SPRING_SQL_INIT_DATA_LOCATIONS: "classpath:import.sql"
  SPRING_SQL_INIT_MODE: "always"
  SPRING_SQL_INIT_CONTINUE_ON_ERROR: "true"
  KEYCLOAK_REALM: "ebs-realm"
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak-auth.esb.svc.cluster.local/auth/"
  #KEYCLOAK_USERNAME: "ebs-superadmin"
  #KEYCLOAK_PASSWORD: "ebs-superadmin"
  KEYCLOAK_SSL_REQUIRED: "external"
  KEYCLOAK_RESOURCE: "ebs-app"
  KEYCLOAK_BEARER_ONLY: "true"
  KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS: "true"
  KEYCLOAK_PRINCIPAL_ATTRIBUTE: "email"
  KEYCLOAK_CORS: "true"
  KEYCLOAK_GRANT_TYPE: "password"
  KEYCLOAK_CLIENT_URL: "http://app.easybulk.intra"
  KEYCLOAK_SECURITY_CONSTRAINTS_0_AUTH_ROLES_0: "user"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: "https://keycloak-auth/auth/realms/ebs-realm"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak-auth/auth/realms/ebs-realm/protocol/openid-connect/certs"
  SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS: "false"
  SPRING_DATA_MONGODB_URI:  "mongodb://mongodb:mongodb@mongodb-svc.esb.svc.cluster.local/easybulk?authSource=easybulk&replicaSet=mongodb&ssl=false"
  SECRET_KEY: "bbe7d157-a253-4094-9759-06a8236543f9"
  API_KEY: "d7627bb6-2292-4911-82e1-615c0ed3eebb"
  CENTRIFUGO_HOST: "https://ws.easybulk.intra"
  CENTRIFUGO_POST_API: "/api/publish"
  SERVER_SERVLET_CONTEXT_PATH: "/v1"
  DOCKER_SHARED_DATA: "/data"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: "easybulk3@gmail.com"
  SPRING_MAIL_PASSWORD: "qhkupwgornfsshfl"
  SPRING_MAIL_PROTOCOL: "smtp"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  KANNEL_SMSC: "simulator"

  #LOGGING.LEVEL.ROOT: "DEBUG"
  INVITE.LINK: "https://app.easybulk.intra"

  AIRFLOW_API_URL: "http://webserver.esb.svc.cluster.local:7071/api/v1"
  #AIRFLOW_USER: "admin"
  #AIRFLOW_PASSWORD: "admin"
  QUARKUS_HTTP_ACCESS_LOG_ENABLED: "true"
  QUARKUS_HTTP_ACCESS_LOG_PATTERN: "%h %l %u %r %s %b %t \"%{i,Referer}\" \"%{i,User-Agent}\""
