apiVersion: v1
kind: Service
metadata:
  name: mycaddy-caddy-ingress-controller
  namespace: esb
  labels:
    helm.sh/chart: caddy-ingress-controller-1.3.0
    app.kubernetes.io/name: caddy-ingress-controller
    app.kubernetes.io/instance: mycaddy
    app.kubernetes.io/version: "v0.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: 32080
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      nodePort: 32443
  selector:
    app.kubernetes.io/name: caddy-ingress-controller
    app.kubernetes.io/instance: mycaddy

