apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
  namespace: esb
  labels:
    app: proxysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: proxysql
          image: registry.tritux.com/easybulk3/proxysql:v3.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/proxysql
            - name: proxysql-config
              mountPath: /etc/proxysql/proxysql.cnf
              subPath: proxysql.cnf
      volumes:
        - name: data-volume
          hostPath:
            path: /mnt/nfs-share/kannel/proxysql/data
            type: Directory
        - name: proxysql-config
          configMap:
            name: proxysql-config

