apiVersion: batch/v1
kind: Job
metadata:
  name: init-crunchy-databases
  namespace: esb
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init-dbs
        image: postgres:17
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -euo pipefail

            echo "Creating databases if not exist..."

            if ! PGPASSWORD=$PG_SUPER_PASS psql -h $PG_HOST -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='superset'" | grep -q 1; then
              echo "Creating database superset"
              PGPASSWORD=$PG_SUPER_PASS psql -h $PG_HOST -U postgres -c "CREATE DATABASE superset;"
              PGPASSWORD=$PG_SUPER_PASS psql -h $PG_HOST -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE superset TO postgres;"
            else
              echo "Database superset already exists"
            fi

            if ! PGPASSWORD=$PG_SUPER_PASS psql -h $PG_HOST -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='airflow'" | grep -q 1; then
              echo "Creating database airflow"
              PGPASSWORD=$PG_SUPER_PASS psql -h $PG_HOST -U postgres -c "CREATE DATABASE airflow;"
              PGPASSWORD=$PG_SUPER_PASS psql -h $PG_HOST -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE airflow TO airflowuser;"
            else
              echo "Database airflow already exists"
            fi
        env:
        - name: PG_HOST
          value: "postgres-primary.esb.svc"
        - name: PG_SUPER_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-pguser-postgres
              key: password

