apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-variables
  namespace: esb
data:
  AIRFLOW__CORE__FERNET_KEY: B7SgOjI91jhcqQ1HIc0L6BXnOR2T0xv8DAtlc6W5bI0=
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW_VAR__METADATA_DB_SCHEMA: airflow
  AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: "10"
  AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
  AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: airflow-variables
  AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS: ""
  AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: "10"
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
  AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
  AIRFLOW__KUBERNETES__IN_CLUSTER: "True"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__KUBERNETES__NAMESPACE: "esb"
  AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
  AIRFLOW__WEBSERVER__SECRET_KEY: "SECRET"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"

  AIRFLOW__CELERY__WORKER_CONCURRENCY: "8"
  AIRFLOW__SCHEDULER__PARSING_PROCESSES: "32"
  AIRFLOW__CORE__DAG_CONCURRENCY: "256"
  AIRFLOW__CORE__PARALLELISM: "128"
  AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor"
  max_active_runs: "4"
  AIRFLOW_CONN_MONGODB: mongodb://mongodb:mongodb@mongodb-svc.esb.svc.cluster.local/easybulk?authSource=easybulk&replicaSet=mongodb&ssl=false
  AIRFLOW_CONN_MYSQLDB: mysql://ebs-app:root1@mysql.esb.svc.cluster.local:6446/easybulk?local_infile=true
  AIRFLOW_CONN_BEARER_BOX: http://bearerbox.esb.svc.cluster.local:13000
  AIRFLOW_API_URL: https://airflow.easybulk.intra/api/v1

  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:postgres@postgres-ha.esb.svc.cluster.local:5432/airflow"
  AIRFLOW_CONN_METADATA_DB: "db+postgresql://postgres:postgres@postgres-ha.esb.svc.cluster.local:5432/airflow"

  SPOOL_SCHEDULE: "60"
  SEARCH_FOR_CAMPAGNE_TO_PROCESS_SCHEDULE: "10"
  SEARCH_FOR_CAMPAGNE_TO_PROCESS_LIMIT: "10"
  SEARCH_FOR_CAMPAGNE_TO_COMPLETE_SCHEDULE: "60"
  SEARCH_FOR_CAMPAGNE_TO_COMPLETE_LIMIT: "10"
  SEARCH_FOR_READY_CAMPAGNE_SCHEDULE: "60"
  SEARCH_FOR_READY_CAMPAGNE_LIMIT: "10"
  SYNC_CONTACt_WITH_SMS_ACK: "60"
  NOTIFICATION_POKE: "5"
  FILE_MAX_ACTIVE_RUN: "10"
  CAMPAGNE_MAX_ACTIVE_RUN: "10"
  FILE_SAVE_CHUNK_SIZE: "10000"
  FILES_EXTENSION: ".csv"
  FILE_VALIDATION_CHUNK_SIZE: "10000"
  PROCESS_CAMPAGNE_CHUNK_SIZE: "1000"
  SAVE_CAMPAGNE_CHUNK_SIZE: "1000"
  READ_ACK_CHUNK: "10000"
  PROCESS_CHUNK_SIZE: "100"
  SPOOL_MAX_QUEUED: "1000"

  CENTRIFUGO_HOST: "http://centrifugo.esb.svc.cluster.local:8000"
  CENTRIFUGO_POST_API: "/api/publish"
  API_KEY: "d7627bb6-2292-4911-82e1-615c0ed3eebb"

  # Reference pod template 
  AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE: "/opt/airflow/pod_templates/template.yaml"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS: "True"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE: "False"

  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY: "registry.tritux.com/easybulk3/airflow"
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG: "v3.0.2"
