apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-rolebinding
  namespace: esb
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: esb
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io
