# Source: caddy-ingress-controller/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: caddy-ingress-controller-role-binding
  namespace: esb
roleRef:
  kind: ClusterRole
  name: caddy-ingress-controller-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: caddy-ingress-controller
  namespace: esb
