# Source: caddy-ingress-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caddy-ingress-controller
  namespace: esb
  labels:
    helm.sh/chart: caddy-ingress-controller-1.3.0
    app.kubernetes.io/name: caddy-ingress-controller
    app.kubernetes.io/instance: mycaddy
    app.kubernetes.io/version: "v0.2.1"
    app.kubernetes.io/managed-by: Helm
