apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-cache
          image: redis:7
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          command:
            - "redis-server"
            - "--appendonly"
            - "yes"
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        storageClassName: "nfs-client"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

