apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: esb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: superset
        image: registry.tritux.com/easybulk3/superset:v3.0.1
        imagePullPolicy: Always
        command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
        ports:
        - containerPort: 8088
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-pguser-postgres
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pguser-postgres
              key: password
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-pguser-postgres
              key: host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-pguser-postgres
              key: port
        - name: DATABASE_DB
          valueFrom:
            secretKeyRef:
              name: postgres-pguser-postgres
              key: dbname
        - name: SUPERSET_ENV
          value: production
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: superset-secrets
              key: SUPERSET_SECRET_KEY
        envFrom:
        - configMapRef:
            name: superset-config
        securityContext:
          runAsUser: 0

