apiVersion: batch/v1
kind: Job
metadata:
  name: superset-init
  namespace: esb
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: superset-init
          image: registry.tritux.com/easybulk3/superset:v3.0.1
          command: ["/app/docker/docker-init.sh"]
          envFrom:
            - configMapRef:
                name: superset-config
            - secretRef:
                name: superset-secrets
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: port
            - name: DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: dbname

