  
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
  namespace: esb
provisioner: nfs.csi.k8s.io
parameters:
  server: esb-nfs
  share: /srv/nfs/share    
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

